### Lista categorias
GET http://127.0.0.1:3000/api/categoria
Accept: application/json

### Guardar Categoria
POST http://127.0.0.1:3000/api/categoria
Accept: application/json
Content-Type: application/json

{
    "nombre": "PRUEBA",
    "detalle": "prueba de prueba"
}

### Mostrar Categoria
GET http://127.0.0.1:3000/api/categoria/2
Accept: application/json


### Modificar Categoria
PUT http://127.0.0.1:3000/api/categoria/3
Accept: application/json
Content-Type: application/json

{
  "nombre": "JUGUETES",
  "detalle": "Juguetes de prueba"
}

### Eliminar Categoria
DELETE http://127.0.0.1:3000/api/categoria/7
Accept: application/json
